spring:
  mail:
    host: smtp.poczta.onet.pl
    port: 465
    username: *@onet.pl
    password: ***
    properties:
      mail.smtp.ssl.enable: true
      smtp.auth: true

logging:
  level:
    com.javastart.webform: DEBUG


